### PR TITLE
Minor updates and aesthetic changes.

### PR DESCRIPTION
**Pull request by mesaugat**
Minor updates and aesthetic changes.

### CODE REVIEW

**Comment by squgeim** [comment]
I'm not sure if only loading the content script only on video pages works. I had tried it before but since there is no new page load when going from the home page to the video page, the content script is not loaded there.

**Comment by mesaugat** [comment]
Yes, you maybe right.

**Comment by mesaugat** [comment]
Might need to log something to the console and see if it works every time.

**Comment by mesaugat** [comment]
Seems like it won't work. https://stackoverflow.com/a/18398921/2352587

I'll revert that change. 😭

**Pull request merged**
